In [ ]:
from random import random 
import numpy as np
def randomize_matrix(n):
    return [[random() for _ in range(n)] for _ in range(n)]


print(randomize_matrix(3))
np.dot(randomize_matrix(3), randomize_matrix(3))



[[0.7710113671722088, 0.7445330411149057, 0.9104923809094367], [0.6093258427584297, 0.4907162495533478, 0.0006431735837549857], [0.12586766661512516, 0.41756826318561646, 0.13575662456184578]]
[[ 30  24  18]
 [ 84  69  54]
 [138 114  90]]
[[30, 24, 18], [84, 69, 54], [138, 114, 90]]


In [37]:
# def binet(A, B):
#     C = [[0 for _ in range(n)] for _ in range(n)]
#     def rec(rowA, colA, An, rowB, colB, Bn):
#         nonlocal A, B
#         prA = (rowA + An) / 2
#         pcA = (colA + An) / 2
#         prB = (rowA + Bn) / 2
#         pcB = (colC + Bn) / 2
#         rec(
#         if An == 1 and Bn == 1:
#             C[rowA][colB] = A[rowA][colA] * B[rowB][colB] + A[rowA][colA] * B[rowB][colB]
#             C12 = A11 * B11 + A12 * B21
#             C21 = A11 * B11 + A12 * B21
#             C22 = A11 * B11 + A12 * B21
            
        
        
        
#     rec(len(A), len(A), len(B), len(B))

def binet(A, B):
    n = len(A)
    
    if n == 1:
        return np.array([[A[0, 0] * B[0, 0]]])
    A = np.array(A)
    B = np.array(B)
    
    mid = n // 2
    
    A11 = A[:mid, :mid]
    A12 = A[:mid, mid:]
    A21 = A[mid:, :mid]
    A22 = A[mid:, mid:]
    
    B11 = B[:mid, :mid]
    B12 = B[:mid, mid:]
    B21 = B[mid:, :mid]
    B22 = B[mid:, mid:]
    
    C11 = binet(A11, B11) + binet(A12, B21)
    C12 = binet(A11, B12) + binet(A12, B22)
    C21 = binet(A21, B11) + binet(A22, B21)
    C22 = binet(A21, B12) + binet(A22, B22)
    
    C = np.zeros((n, n))
    C[:mid, :mid] = C11
    C[:mid, mid:] = C12
    C[mid:, :mid] = C21
    C[mid:, mid:] = C22
    
    return C

In [38]:
A = [[1,2,3,4],
     [5,6,7,8],
     [9,10,11,12],
     [13,14,15,16]]

B = [[1,2,3,4],
     [5,6,7,8],
     [9,10,11,12],
     [13,14,15,16]]
C = [[90, 100, 110, 120], [202, 228, 254, 280], [314, 356, 398, 440], [426, 484, 542, 600]]

print(np.dot(A, B))
print(C)
print(binet(A, B))

[[ 90 100 110 120]
 [202 228 254 280]
 [314 356 398 440]
 [426 484 542 600]]
[[90, 100, 110, 120], [202, 228, 254, 280], [314, 356, 398, 440], [426, 484, 542, 600]]
[[ 90. 100. 110. 120.]
 [202. 228. 254. 280.]
 [314. 356. 398. 440.]
 [426. 484. 542. 600.]]


In [ ]:

A = [[1,2,3],
     [4,5,6],
     [7,8,9]]

B = [[9,8,7],
     [6,5,4],
     [3,2,1]]

C = [[30, 24, 18], [84, 69, 54], [138, 114, 90]]
print(np.dot(A, B))
print(C)

In [28]:
# Function to add two matrices of same dimensions r×c
def add(mat1, mat2):
    r = len(mat1)
    c = len(mat1[0])

    # Initialize result matrix with dimensions r×c
    res = [[0] * c for _ in range(r)]

    # Perform element-wise addition
    for i in range(r):
        for j in range(c):
            res[i][j] = mat1[i][j] + mat2[i][j]

    return res

# Function to multiply mat1 (n×m) with mat2 (m×q)
def multiply(mat1, mat2):
    n = len(mat1)
    m = len(mat1[0])
    q = len(mat2[0])

    # Initialize result matrix with dimensions n×q
    res = [[0] * q for _ in range(n)]

    # Matrix multiplication logic
    for i in range(n):
        for j in range(q):
            for k in range(m):
                res[i][j] += mat1[i][k] * mat2[k][j]

    return res
# mat1 = [
#     [1, 2, 3],
#     [4, 5, 6]
# ]

# mat2 = [
#     [7, 8],
#     [9, 10],
#     [11, 12]
# ]

# res = multiply(mat1, mat2)

# for row in res:
#     print(" ".join(map(str, row)))

A = [[1,2,3,4],
     [5,6,7,8],
     [9,10,11,12],
     [13,14,15,16]]

B = [[1,2,3,4],
     [5,6,7,8],
     [9,10,11,12],
     [13,14,15,16]]
C = [[90, 100, 110, 120], [202, 228, 254, 280], [314, 356, 398, 440], [426, 484, 542, 600]]

print(np.dot(A, B))
print(C)
print(multiply(A, B))

[[ 90 100 110 120]
 [202 228 254 280]
 [314 356 398 440]
 [426 484 542 600]]
[[90, 100, 110, 120], [202, 228, 254, 280], [314, 356, 398, 440], [426, 484, 542, 600]]
[[90, 100, 110, 120], [202, 228, 254, 280], [314, 356, 398, 440], [426, 484, 542, 600]]
