In [1]:
import numpy as np
import common
from common import reset_counters, check_mat, randomize_matrix
from multiplication import strassen
# from gaussian_elimination import recursive_gaussian_elimination, recursive_determinant, recursive_determinant_block
from functions import gaussian_elimination

# Import counters for easy access
counter_add = common.counter_add
counter_mul = common.counter_mul
counter_sub = common.counter_sub


## Recursive Gaussian Elimination Test


In [2]:
# Test recursive Gaussian elimination with a simple 3x3 system
A = np.array([[2.0, 1.0, 0.0],
              [1.0, 2.0, 1.0],
              [0.0, 1.0, 2.0]], dtype=float)

b = np.array([[1.0], [2.0], [3.0]])

reset_counters()

x = gaussian_elimination(A, b, strassen)

print("Original matrix A:")
print(A)
print("\nRight-hand side b:")
print(b)
print("\nSolution x (Ax = b):")
print(x)
print("\nVerification (A * x should equal b):")
Ax = A @ x
print("A * x =")
print(Ax)
print("\nExpected b:")
print(b)
print("\nDifference:")
print(np.abs(Ax - b))
print("\nIs correct?", np.allclose(Ax, b, atol=1e-9))
print("\nCounters:")
print(f"Additions: {common.counter_add}, Multiplications: {common.counter_mul}, Subtractions: {common.counter_sub}")


Original matrix A:
[[2. 1. 0.]
 [1. 2. 1.]
 [0. 1. 2.]]

Right-hand side b:
[[1.]
 [2.]
 [3.]]

Solution x (Ax = b):
[[0.5]
 [0. ]
 [1.5]]

Verification (A * x should equal b):
A * x =
[[1.]
 [2.]
 [3.]]

Expected b:
[[1.]
 [2.]
 [3.]]

Difference:
[[0.]
 [0.]
 [0.]]

Is correct? True

Counters:
Additions: 81, Multiplications: 118, Subtractions: 11


In [3]:
# Test with multiple right-hand sides
A = np.array([[4.0, 1.0, 2.0],
              [1.0, 3.0, 0.5],
              [2.0, 0.5, 5.0]], dtype=float)

b_multi = np.array([[1.0, 2.0], [2.0, 3.0], [3.0, 4.0]])

reset_counters()

x_multi = gaussian_elimination(A, b_multi, strassen)

print("Matrix A:")
print(A)
print("\nRight-hand sides (2 columns):")
print(b_multi)
print("\nSolutions (2 columns):")
print(x_multi)
print("\nVerification:")
print("A * x[:,0] =", A @ x_multi[:, [0]])
print("Expected b[:,0] =", b_multi[:, [0]])
print("A * x[:,1] =", A @ x_multi[:, [1]])
print("Expected b[:,1] =", b_multi[:, [1]])
print("\nBoth correct?", np.allclose(A @ x_multi, b_multi, atol=1e-9))
print("\nCounters:")
print(f"Additions: {common.counter_add}, Multiplications: {common.counter_mul}, Subtractions: {common.counter_sub}")


Matrix A:
[[4.  1.  2. ]
 [1.  3.  0.5]
 [2.  0.5 5. ]]

Right-hand sides (2 columns):
[[1. 2.]
 [2. 3.]
 [3. 4.]]

Solutions (2 columns):
[[-0.22159091 -0.10227273]
 [ 0.63636364  0.90909091]
 [ 0.625       0.75      ]]

Verification:
A * x[:,0] = [[1.]
 [2.]
 [3.]]
Expected b[:,0] = [[1.]
 [2.]
 [3.]]
A * x[:,1] = [[2.]
 [3.]
 [4.]]
Expected b[:,1] = [[2.]
 [3.]
 [4.]]

Both correct? True

Counters:
Additions: 111, Multiplications: 162, Subtractions: 11


## Compare with NumPy


In [4]:
# Compare Gaussian elimination with NumPy's solve
A = np.array([[4.0, 1.0, 2.0],
              [1.0, 3.0, 0.5],
              [2.0, 0.5, 5.0]], dtype=float)

b = np.array([[1.0], [2.0], [3.0]])

print("Matrix A:")
print(A)
print("\nRight-hand side b:")
print(b)

print("\n" + "="*60)
print("Recursive Gaussian elimination:")
print("="*60)
reset_counters()
x_rec = gaussian_elimination(A, b, strassen)
print("Solution x:")
print(x_rec)
print(f"\nOperations: Add={common.counter_add}, Mul={common.counter_mul}, Sub={common.counter_sub}")

print("\n" + "="*60)
print("NumPy solve:")
print("="*60)
x_np = np.linalg.solve(A, b)
print("Solution x:")
print(x_np)

print("\n" + "="*60)
print("Comparison:")
print("="*60)
print("Difference:", np.abs(x_rec - x_np))
print("Are solutions close?", np.allclose(x_rec, x_np, atol=1e-9))


Matrix A:
[[4.  1.  2. ]
 [1.  3.  0.5]
 [2.  0.5 5. ]]

Right-hand side b:
[[1.]
 [2.]
 [3.]]

Recursive Gaussian elimination:
Solution x:
[[-0.22159091]
 [ 0.63636364]
 [ 0.625     ]]

Operations: Add=81, Mul=118, Sub=11

NumPy solve:
Solution x:
[[-0.22159091]
 [ 0.63636364]
 [ 0.625     ]]

Comparison:
Difference: [[0.]
 [0.]
 [0.]]
Are solutions close? True
