In [1]:
import numpy as np
import common
from common import reset_counters, check_mat, randomize_matrix
from multiplication import binet, strassen
from gaussian_elimination import recursive_gaussian_elimination, recursive_determinant, recursive_determinant_block

# Import counters for easy access
counter_add = common.counter_add
counter_mul = common.counter_mul
counter_sub = common.counter_sub


## Recursive Gaussian Elimination Test


In [2]:
# Test recursive Gaussian elimination with a simple 3x3 system
A = np.array([[2.0, 1.0, 0.0],
              [1.0, 2.0, 1.0],
              [0.0, 1.0, 2.0]], dtype=float)

b = np.array([[1.0], [2.0], [3.0]])

reset_counters()

U, P, x = recursive_gaussian_elimination(A, binet, b)

print("Original matrix A:")
print(A)
print("\nRight-hand side b:")
print(b)
print("\nUpper triangular U (row echelon form):")
print(U)
print("\nSolution x (Ax = b):")
print(x)
print("\nVerification (A * x should equal b):")
Ax = A @ x
print("A * x =")
print(Ax)
print("\nExpected b:")
print(b)
print("\nDifference:")
print(np.abs(Ax - b))
print("\nIs correct?", np.allclose(Ax, b, atol=1e-9))
print("\nCounters:")
print(f"Additions: {common.counter_add}, Multiplications: {common.counter_mul}, Subtractions: {common.counter_sub}")


Original matrix A:
[[2. 1. 0.]
 [1. 2. 1.]
 [0. 1. 2.]]

Right-hand side b:
[[1.]
 [2.]
 [3.]]

Upper triangular U (row echelon form):
[[2.         1.         0.        ]
 [0.         1.5        1.        ]
 [0.         0.         1.33333333]]

Solution x (Ax = b):
[[5.00000000e-01]
 [1.48029737e-16]
 [1.50000000e+00]]

Verification (A * x should equal b):
A * x =
[[1.]
 [2.]
 [3.]]

Expected b:
[[1.]
 [2.]
 [3.]]

Difference:
[[0.0000000e+00]
 [0.0000000e+00]
 [4.4408921e-16]]

Is correct? True

Counters:
Additions: 14, Multiplications: 38, Subtractions: 5


In [3]:
# Test with multiple right-hand sides
A = np.array([[4.0, 1.0, 2.0],
              [1.0, 3.0, 0.5],
              [2.0, 0.5, 5.0]], dtype=float)

b_multi = np.array([[1.0, 2.0], [2.0, 3.0], [3.0, 4.0]])

reset_counters()

U, P, x_multi = recursive_gaussian_elimination(A, binet, b_multi)

print("Matrix A:")
print(A)
print("\nRight-hand sides (2 columns):")
print(b_multi)
print("\nSolutions (2 columns):")
print(x_multi)
print("\nVerification:")
print("A * x[:,0] =", A @ x_multi[:, [0]])
print("Expected b[:,0] =", b_multi[:, [0]])
print("A * x[:,1] =", A @ x_multi[:, [1]])
print("Expected b[:,1] =", b_multi[:, [1]])
print("\nBoth correct?", np.allclose(A @ x_multi, b_multi, atol=1e-9))
print("\nCounters:")
print(f"Additions: {common.counter_add}, Multiplications: {common.counter_mul}, Subtractions: {common.counter_sub}")


Matrix A:
[[4.  1.  2. ]
 [1.  3.  0.5]
 [2.  0.5 5. ]]

Right-hand sides (2 columns):
[[1. 2.]
 [2. 3.]
 [3. 4.]]

Solutions (2 columns):
[[-0.22159091 -0.10227273]
 [ 0.63636364  0.90909091]
 [ 0.625       0.75      ]]

Verification:
A * x[:,0] = [[1.]
 [2.]
 [3.]]
Expected b[:,0] = [[1.]
 [2.]
 [3.]]
A * x[:,1] = [[2.]
 [3.]
 [4.]]
Expected b[:,1] = [[2.]
 [3.]
 [4.]]

Both correct? True

Counters:
Additions: 20, Multiplications: 50, Subtractions: 5


## Recursive Determinant Calculation Test


In [4]:
# Test recursive determinant with a simple 3x3 matrix
A = np.array([[4.0, 1.0, 2.0],
              [1.0, 3.0, 0.5],
              [2.0, 0.5, 5.0]], dtype=float)

reset_counters()
det_rec = recursive_determinant_block(A, binet)
det_np = np.linalg.det(A)

print("Matrix A:")
print(A)
print(f"\nRecursive determinant: {det_rec:.10f}")
print(f"NumPy determinant:     {det_np:.10f}")
print(f"Difference:             {abs(det_rec - det_np):.2e}")
print("\nIs correct?", np.allclose(det_rec, det_np, atol=1e-9))
print("\nCounters:")
print(f"Additions: {common.counter_add}, Multiplications: {common.counter_mul}, Subtractions: {common.counter_sub}")


Matrix A:
[[4.  1.  2. ]
 [1.  3.  0.5]
 [2.  0.5 5. ]]

Recursive determinant: 44.0000000000
NumPy determinant:     44.0000000000
Difference:             1.42e-14

Is correct? True

Counters:
Additions: 10, Multiplications: 26, Subtractions: 5


In [7]:
# Test with a 4x4 matrix
A = np.array([[4.0, 1.0, 2.0, 0.5],
              [1.0, 3.0, 0.5, 1.0],
              [2.0, 0.5, 5.0, 1.0],
              [0.5, 1.0, 1.0, 2.0]], dtype=float)

reset_counters()
det_rec = recursive_determinant_block(A, binet)
det_np = np.linalg.det(A)

print("Matrix A:")
print(A)
print(f"\nRecursive determinant: {det_rec:.10f}")
print(f"NumPy determinant:     {det_np:.10f}")
print(f"Difference:             {abs(det_rec - det_np):.2e}")
print("\nIs correct?", np.allclose(det_rec, det_np, atol=1e-9))
print("\nCounters:")
print(f"Additions: {common.counter_add}, Multiplications: {common.counter_mul}, Subtractions: {common.counter_sub}")


Matrix A:
[[4.  1.  2.  0.5]
 [1.  3.  0.5 1. ]
 [2.  0.5 5.  1. ]
 [0.5 1.  1.  2. ]]

Recursive determinant: 66.8125000000
NumPy determinant:     66.8125000000
Difference:             2.84e-14

Is correct? True

Counters:
Additions: 24, Multiplications: 52, Subtractions: 9


## Verify recursive Gaussian elimination and determinant for various matrix sizes


In [9]:
GREEN = '\033[92m'
RED = '\033[91m'
ENDCOLOR = '\033[0m'

test_count = 20
correct_count_ge = 0
correct_count_det = 0

for n in range(1, test_count + 1):
    print(f"Verifying n = {n}")
    
    # Generate a random invertible matrix
    A = np.random.rand(n, n) * 0.5 + np.eye(n) * 2.0
    b = np.random.rand(n, 1)
    
    # Test Gaussian elimination
    reset_counters()
    try:
        U, P, x = recursive_gaussian_elimination(A, binet, b)
        Ax = A @ x
        if check_mat(Ax, b, tol=1e-5):
            correct_count_ge += 1
        else:
            print(f"  Warning: Gaussian elimination failed for n={n}")
    except Exception as e:
        print(f"  Error in Gaussian elimination for n={n}: {e}")
    
    # Test determinant
    reset_counters()
    try:
        det_rec = recursive_determinant_block(A, binet)
        det_np = np.linalg.det(A)
        if np.allclose(det_rec, det_np, atol=1e-5):
            correct_count_det += 1
        else:
            print(f"  Warning: Determinant incorrect for n={n}")
    except Exception as e:
        print(f"  Error in determinant for n={n}: {e}")

print(f'\nGaussian elimination: {correct_count_ge}/{test_count} correct')
if correct_count_ge == test_count:
    print(f'{GREEN}Gaussian elimination: Success!{ENDCOLOR}')
else:
    print(f'{RED}Gaussian elimination: Test failed!{ENDCOLOR}')

print(f'\nDeterminant: {correct_count_det}/{test_count} correct')
if correct_count_det == test_count:
    print(f'{GREEN}Determinant: Success!{ENDCOLOR}')
else:
    print(f'{RED}Determinant: Test failed!{ENDCOLOR}')


Verifying n = 1
Verifying n = 2
Verifying n = 3
Verifying n = 4
Verifying n = 5
Verifying n = 6
Verifying n = 7
Verifying n = 8
Verifying n = 9
Verifying n = 10
Verifying n = 11
Verifying n = 12
Verifying n = 13
Verifying n = 14
Verifying n = 15
Verifying n = 16
Verifying n = 17
Verifying n = 18
Verifying n = 19
Verifying n = 20

Gaussian elimination: 20/20 correct
Gaussian elimination: Success!

Determinant: 20/20 correct
Determinant: Success!


## Compare with NumPy


In [11]:
# Compare Gaussian elimination with NumPy's solve
A = np.array([[4.0, 1.0, 2.0],
              [1.0, 3.0, 0.5],
              [2.0, 0.5, 5.0]], dtype=float)

b = np.array([[1.0], [2.0], [3.0]])

print("Matrix A:")
print(A)
print("\nRight-hand side b:")
print(b)

print("\n" + "="*60)
print("Recursive Gaussian elimination:")
print("="*60)
reset_counters()
U_rec, P_rec, x_rec = recursive_gaussian_elimination(A, binet, b)
print("Solution x:")
print(x_rec)
print(f"\nOperations: Add={common.counter_add}, Mul={common.counter_mul}, Sub={common.counter_sub}")

print("\n" + "="*60)
print("NumPy solve:")
print("="*60)
x_np = np.linalg.solve(A, b)
print("Solution x:")
print(x_np)

print("\n" + "="*60)
print("Comparison:")
print("="*60)
print("Difference:", np.abs(x_rec - x_np))
print("Are solutions close?", np.allclose(x_rec, x_np, atol=1e-9))


Matrix A:
[[4.  1.  2. ]
 [1.  3.  0.5]
 [2.  0.5 5. ]]

Right-hand side b:
[[1.]
 [2.]
 [3.]]

Recursive Gaussian elimination:
Solution x:
[[-0.22159091]
 [ 0.63636364]
 [ 0.625     ]]

Operations: Add=14, Mul=38, Sub=5

NumPy solve:
Solution x:
[[-0.22159091]
 [ 0.63636364]
 [ 0.625     ]]

Comparison:
Difference: [[0.]
 [0.]
 [0.]]
Are solutions close? True


## Test with larger matrices


In [13]:
import time

test_sizes = [8, 16, 32]

for n in test_sizes:
    print(f"\nTesting {n}x{n} matrix:")
    print("-" * 50)
    
    # Generate a random matrix
    np.random.seed(42)
    A = np.random.rand(n, n) * 0.5 + np.eye(n) * 2.0
    b = np.random.rand(n, 1)
    
    # Test Gaussian elimination
    reset_counters()
    start_time = time.time()
    U, P, x = recursive_gaussian_elimination(A, binet, b)
    elapsed_time_ge = time.time() - start_time
    
    Ax = A @ x
    max_diff_ge = np.max(np.abs(Ax - b))
    is_correct_ge = np.allclose(Ax, b, atol=1e-9)
    
    print(f"Gaussian elimination:")
    print(f"  Time: {elapsed_time_ge*1000:.2f} ms")
    print(f"  Max difference: {max_diff_ge:.2e}")
    print(f"  Is correct: {is_correct_ge}")
    print(f"  Operations: Add={common.counter_add}, Mul={common.counter_mul}, Sub={common.counter_sub}")
    
    # Test determinant
    reset_counters()
    start_time = time.time()
    det_rec = recursive_determinant_block(A, binet)
    elapsed_time_det = time.time() - start_time
    
    det_np = np.linalg.det(A)
    max_diff_det = abs(det_rec - det_np)
    is_correct_det = np.allclose(det_rec, det_np, atol=1e-9)
    
    print(f"\nDeterminant:")
    print(f"  Time: {elapsed_time_det*1000:.2f} ms")
    print(f"  Recursive: {det_rec:.10f}")
    print(f"  NumPy:      {det_np:.10f}")
    print(f"  Difference: {max_diff_det:.2e}")
    print(f"  Is correct: {is_correct_det}")
    print(f"  Operations: Add={common.counter_add}, Mul={common.counter_mul}, Sub={common.counter_sub}")



Testing 8x8 matrix:
--------------------------------------------------
Gaussian elimination:
  Time: 1.40 ms
  Max difference: 1.11e-16
  Is correct: True
  Operations: Add=248, Mul=424, Sub=28

Determinant:
  Time: 2.09 ms
  Recursive: 491.0956686506
  NumPy:      491.0956686506
  Difference: 5.68e-14
  Is correct: True
  Operations: Add=360, Mul=599, Sub=52

Testing 16x16 matrix:
--------------------------------------------------
Gaussian elimination:
  Time: 7.07 ms
  Max difference: 3.33e-16
  Is correct: True
  Operations: Add=2032, Mul=3088, Sub=120

Determinant:
  Time: 12.20 ms
  Recursive: 226820.3666408171
  NumPy:      226820.3666408169
  Difference: 1.46e-10
  Is correct: True
  Operations: Add=3616, Mul=5611, Sub=252

Testing 32x32 matrix:
--------------------------------------------------
Gaussian elimination:
  Time: 33.36 ms
  Max difference: 2.22e-16
  Is correct: True
  Operations: Add=16352, Mul=23328, Sub=496

Determinant:
  Time: 76.22 ms
  Recursive: 20365727621.